# Generated by Django 4.2.5 on 2023-09-30 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='contact_attachment_file',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='contact_status',
        ),
    ]
